### ISSUE TITLE
Midterm Review (Mind map)

### ISSUE THREAD

**Issue by ErinGeorge** [PhilChodrow/PIC16A#11]
Two issues I noticed with the mind map:

1) Students didn't usually think about connections beyond immediate neighbors on the map unless prompted.  Shuffling the topics a bit or explicitly suggesting that they draw connections far away would encourage them to think more deeply about whether or not two concepts relate as opposed to just drawing arrows between adjacent things.

2) Several groups were disinterested in the mind map and reported that they didn't think it was very helpful.  I expect many of those students probably will do well on the exam anyway, but they do have a good point in that the knowledge tested by the mindmap does not really directly translate to the ability to perform well on the exam.

**Comment by PhilChodrow** [comment]
This is very useful stuff to know. 

1. Maybe the lightest way to address this would be to draw a few long arrows (as well as a few short ones) on the example. 
2. Yeah, this makes sense, although I'm not sure if I fully agree about "direct translation" to the exam. Maybe I should actually try pulling that data to see if there's any kind of correlation between map quality and exam performance (although in principle this correlation could be induced by many confounders). 

Going to think about this one a bit.

**Comment by PhilChodrow** [comment]
Oh, an alternative occurred to me: groups are given the option to either complete the mind-map activity or work a problem from an old exam, with both being available to them in case they want to work on the other one later. 

This gets more workable when we get more old exams. =)

**Comment by PhilChodrow** [comment]
Added two longer arrows in the starting mind-map, and will allow students to choose between the mind map and an old exam problem next time we do this activity.
