### ISSUE TITLE
Misleading exericse

### ISSUE THREAD

**Issue by ErinGeorge** [PhilChodrow/PIC16A#4]
On the second numpy worksheet, the students are supposed to compute all the percentiles at once.  Many groups did not do this because the format of the exercise lent itself to a nice symmetric solution where you use five print statements formatted with the appropriate function call.  I think we should consider revising this, although I don't know the best way.

**Comment by PhilChodrow** [comment]
Just a musing here for now, we could drop the vectorized solution as a desideratum for the problem, since they get to practice this in various other contexts and I'd rather groups not get hung up on the first problem. 

Something to think on a bit in the future.

**Comment by ErinGeorge** [comment]
Yeah.  To add to that, I'm also not too sure if a nuanced understanding of numpy.percentile is particularly useful for them to have.

**Comment by PhilChodrow** [comment]
Dropped vectorized solutions as a desirable approach to the problem, and added sample plots for Parts 2 and 3 so that they can evaluate on their own whether they've produced a correct result.
